title: Cisco Live 2021 - HOLCCT-2100
company_name: Cisco
author:
  name: Lab support email
  email: Site Support: "wxcclabs@cisco.com"
remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
  twitter: Webex
    

header_pages:
  - CiscoLiveLabLibrary.md
